/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/validation/field"
)

const (
	EnforcementModeWarn    = "warn"
	EnforcementModeEnforce = "enforce"
	EnforcementModeAudit   = "audit"
)

type WorkloadTarget struct {
	// NamespaceSelector selects target namespaces.
	// +optional
	NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty"`

	// WorkloadSelector selects workloads or pods inside matching namespaces.
	// +optional
	WorkloadSelector *metav1.LabelSelector `json:"workloadSelector,omitempty"`
}

type ObjectReference struct {
	// Name of the referenced object.
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace of the referenced object. Defaults to the owner namespace.
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

type PolicyAuditSpec struct {
	// Required means the policy must emit auditable records.
	// +optional
	Required bool `json:"required,omitempty"`

	// Level controls the amount of detail retained.
	// +kubebuilder:validation:Enum=summary;full
	// +optional
	Level string `json:"level,omitempty"`
}

type PolicyKeyReleaseSpec struct {
	// Required requires a successful key-release check before execution.
	// +optional
	Required bool `json:"required,omitempty"`

	// TTLSeconds bounds the validity window of a release decision.
	// +kubebuilder:validation:Minimum=0
	// +optional
	TTLSeconds int32 `json:"ttlSeconds,omitempty"`
}

type ConfidentialGPURequirements struct {
	// Vendor identifies the GPU vendor or stack.
	// +kubebuilder:validation:Enum=nvidia;amd;intel
	// +optional
	Vendor string `json:"vendor,omitempty"`

	// DeviceClass identifies the requested class or profile.
	// +optional
	DeviceClass string `json:"deviceClass,omitempty"`

	// DRAClass is the future DRA class name expected in production clusters.
	// +optional
	DRAClass string `json:"draClass,omitempty"`
}

type EvidenceFreshness struct {
	// MaxAgeSeconds is the maximum accepted age.
	// +kubebuilder:validation:Minimum=1
	MaxAgeSeconds int32 `json:"maxAgeSeconds"`

	// Simulated indicates evidence was generated by the local kind simulator.
	// +optional
	Simulated bool `json:"simulated,omitempty"`
}

type PlacementTokenSpec struct {
	// Required means the scheduler/controller must mint a verifiable placement token.
	// +optional
	Required bool `json:"required,omitempty"`

	// TTLSeconds limits token validity.
	// +kubebuilder:validation:Minimum=0
	// +optional
	TTLSeconds int32 `json:"ttlSeconds,omitempty"`
}

type RuntimeExpectation struct {
	// RuntimeClassName is the runtime class expected by policy.
	// +optional
	RuntimeClassName string `json:"runtimeClassName,omitempty"`

	// Simulated indicates the runtime class is a kind-safe simulated mapping.
	// +optional
	Simulated bool `json:"simulated,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="!(has(self.requireConfidentialGPU) && self.requireConfidentialGPU) || has(self.gpu)",message="gpu is required when requireConfidentialGPU is true"
// +kubebuilder:validation:XValidation:rule="!(has(self.requireConfidentialContainers) && self.requireConfidentialContainers) || size(self.allowedRuntimeClasses) > 0",message="allowedRuntimeClasses must not be empty when requireConfidentialContainers is true"
// +kubebuilder:validation:XValidation:rule="!(has(self.keyRelease) && has(self.keyRelease.required) && self.keyRelease.required) || self.keyRelease.ttlSeconds > 0",message="keyRelease.ttlSeconds must be > 0 when keyRelease.required is true"
type ConfidentialInferencePolicySpec struct {
	// Target selects namespaces/workloads protected by the policy.
	Target WorkloadTarget `json:"target"`

	// RequiredTEE enumerates accepted trusted-execution environments.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:items:Enum=TDX;SEV-SNP
	RequiredTEE []string `json:"requiredTEE,omitempty"`

	// RequireConfidentialContainers requires a confidential runtime class.
	// +optional
	RequireConfidentialContainers bool `json:"requireConfidentialContainers,omitempty"`

	// RequireConfidentialGPU requires the GPU section and future DRA integration.
	// +optional
	RequireConfidentialGPU bool `json:"requireConfidentialGPU,omitempty"`

	// GPU describes the expected confidential GPU properties.
	// +optional
	GPU *ConfidentialGPURequirements `json:"gpu,omitempty"`

	// AllowedRuntimeClasses lists allowed runtime classes in production.
	// +optional
	AllowedRuntimeClasses []string `json:"allowedRuntimeClasses,omitempty"`

	// MaxEvidenceAgeSeconds is the freshness limit for attestation evidence.
	// +kubebuilder:validation:Minimum=1
	MaxEvidenceAgeSeconds int32 `json:"maxEvidenceAgeSeconds"`

	// RequireImageDigest requires image references to be digest-pinned.
	// +optional
	RequireImageDigest bool `json:"requireImageDigest,omitempty"`

	// RequireModelDigest requires an immutable model digest annotation.
	// +optional
	RequireModelDigest bool `json:"requireModelDigest,omitempty"`

	// KeyRelease governs conditional key release.
	// +optional
	KeyRelease PolicyKeyReleaseSpec `json:"keyRelease,omitempty"`

	// Audit controls evidence/audit requirements.
	// +optional
	Audit PolicyAuditSpec `json:"audit,omitempty"`

	// EnforcementMode controls policy behavior.
	// +kubebuilder:validation:Enum=warn;enforce;audit
	EnforcementMode string `json:"enforcementMode"`
}

type ConfidentialInferencePolicyStatus struct {
	// ObservedGeneration is the last generation observed by a controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// PolicyHash is the stable hash of the normalized policy spec.
	// +optional
	PolicyHash string `json:"policyHash,omitempty"`

	// EffectiveRuntime maps the requested runtime to a simulated one when needed.
	// +optional
	EffectiveRuntime *RuntimeExpectation `json:"effectiveRuntime,omitempty"`

	// Simulated is true when the policy is currently resolved in local kind mode.
	// +optional
	Simulated bool `json:"simulated,omitempty"`

	// Conditions captures readiness and validation state.
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=cip
type ConfidentialInferencePolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ConfidentialInferencePolicySpec   `json:"spec,omitempty"`
	Status ConfidentialInferencePolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type ConfidentialInferencePolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfidentialInferencePolicy `json:"items"`
}

type AttestationEvidenceSpec struct {
	// SubjectRef identifies the workload, node, device or runtime being attested.
	SubjectRef ObjectReference `json:"subjectRef"`

	// PolicyRef optionally ties evidence to a confidentiality policy.
	// +optional
	PolicyRef *ObjectReference `json:"policyRef,omitempty"`

	// EvidenceType identifies the attestation domain.
	// +kubebuilder:validation:Enum=cpu;gpu;runtime;composite
	EvidenceType string `json:"evidenceType"`

	// TEE identifies the attested trusted execution environment.
	// +kubebuilder:validation:Enum=TDX;SEV-SNP;none
	TEE string `json:"tee"`

	// Runtime captures the expected runtime class and simulation flag.
	// +optional
	Runtime RuntimeExpectation `json:"runtime,omitempty"`

	// Freshness constrains maximum age and simulated mode.
	Freshness EvidenceFreshness `json:"freshness"`

	// EvidenceURI points to the externally stored attestation payload.
	// +optional
	EvidenceURI string `json:"evidenceURI,omitempty"`

	// Digest identifies the immutable evidence digest.
	// +optional
	Digest string `json:"digest,omitempty"`

	// Signatures lists detached or envelope signatures.
	// +optional
	Signatures []string `json:"signatures,omitempty"`

	// Simulated makes local kind evidence explicit.
	// +optional
	Simulated bool `json:"simulated,omitempty"`
}

type AttestationEvidenceStatus struct {
	// ObservedGeneration is the last generation observed by a controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Verified indicates the latest verification outcome.
	// +optional
	Verified bool `json:"verified,omitempty"`

	// Revoked indicates the evidence has been invalidated.
	// +optional
	Revoked bool `json:"revoked,omitempty"`

	// LastVerifiedTime is the last successful verification time.
	// +optional
	LastVerifiedTime *metav1.Time `json:"lastVerifiedTime,omitempty"`

	// ─── Trust-chain fields (Q1 hardening) ──────────────────────────────────
	// These are written ONLY by the central verifier controller, never by a
	// node agent. EvidenceMode is authoritative for downstream consumers.

	// EvidenceMode is "real" only after genuine attestation verification,
	// "simulated" in kind/dev, "unverified" when verification could not run.
	// +kubebuilder:validation:Enum=real;simulated;unverified
	// +optional
	EvidenceMode string `json:"evidenceMode,omitempty"`

	// VerifiedBy names the verifier controller identity that produced this status.
	// +optional
	VerifiedBy string `json:"verifiedBy,omitempty"`

	// VerifierPodUID is the pod UID of the verifier that wrote this status.
	// +optional
	VerifierPodUID string `json:"verifierPodUID,omitempty"`

	// NodeUID binds the evidence to a concrete node object UID.
	// +optional
	NodeUID string `json:"nodeUID,omitempty"`

	// Provider is the attestation provider actually used (maa|simulator).
	// +optional
	Provider string `json:"provider,omitempty"`

	// AttestationType records the attestation flow (guest-attestation|simulated).
	// +optional
	AttestationType string `json:"attestationType,omitempty"`

	// MAATokenHash is the SHA-256 of the raw MAA/guest-attestation token.
	// +optional
	MAATokenHash string `json:"maaTokenHash,omitempty"`

	// ClaimsDigest is a canonical digest of the verified attestation claims.
	// +optional
	ClaimsDigest string `json:"claimsDigest,omitempty"`

	// Nonce echoes the freshness nonce that was verified.
	// +optional
	Nonce string `json:"nonce,omitempty"`

	// IssuedAt / ExpiresAt bound the validity window derived from the claims.
	// +optional
	IssuedAt *metav1.Time `json:"issuedAt,omitempty"`
	// +optional
	ExpiresAt *metav1.Time `json:"expiresAt,omitempty"`

	// FreshnessSeconds is the accepted freshness window in seconds.
	// +optional
	FreshnessSeconds int64 `json:"freshnessSeconds,omitempty"`

	// VerificationStatus is Verified|Failed|Unavailable.
	// +kubebuilder:validation:Enum=Verified;Failed;Unavailable
	// +optional
	VerificationStatus string `json:"verificationStatus,omitempty"`

	// FailureReason explains a Failed/Unavailable verification.
	// +optional
	FailureReason string `json:"failureReason,omitempty"`

	// Conditions captures readiness and verification state.
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

// EvidenceMode constants.
const (
	EvidenceModeReal       = "real"
	EvidenceModeSimulated  = "simulated"
	EvidenceModeUnverified = "unverified"

	VerificationStatusVerified    = "Verified"
	VerificationStatusFailed      = "Failed"
	VerificationStatusUnavailable = "Unavailable"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=aevid
type AttestationEvidence struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AttestationEvidenceSpec   `json:"spec,omitempty"`
	Status AttestationEvidenceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AttestationEvidenceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AttestationEvidence `json:"items"`
}

type AIPlacementDecisionSpec struct {
	// TargetRef identifies the workload or pod being placed.
	TargetRef ObjectReference `json:"targetRef"`

	// PolicyRef references the confidentiality policy used for the decision.
	PolicyRef ObjectReference `json:"policyRef"`

	// EvidenceRef references the evidence used for placement.
	// +optional
	EvidenceRef *ObjectReference `json:"evidenceRef,omitempty"`

	// PlacementToken controls token minting.
	// +optional
	PlacementToken PlacementTokenSpec `json:"placementToken,omitempty"`

	// SchedulerName is the scheduler expected to honor the decision.
	// +optional
	SchedulerName string `json:"schedulerName,omitempty"`
}

type AIPlacementDecisionStatus struct {
	// ObservedGeneration is the last generation observed by a controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Decision is allow, deny or pending.
	// +optional
	Decision string `json:"decision,omitempty"`

	// NodeName is the chosen node when known.
	// +optional
	NodeName string `json:"nodeName,omitempty"`

	// PlacementTokenDigest is a digest of the minted placement token.
	// +optional
	PlacementTokenDigest string `json:"placementTokenDigest,omitempty"`

	// Simulated indicates a kind-local simulated path.
	// +optional
	Simulated bool `json:"simulated,omitempty"`

	// Conditions captures placement state.
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=apd
type AIPlacementDecision struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AIPlacementDecisionSpec   `json:"spec,omitempty"`
	Status AIPlacementDecisionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AIPlacementDecisionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIPlacementDecision `json:"items"`
}

// +kubebuilder:validation:XValidation:rule="!(has(self.requireAttestedEvidence) && self.requireAttestedEvidence) || has(self.evidenceRef)",message="evidenceRef is required when requireAttestedEvidence is true"
// +kubebuilder:validation:XValidation:rule="!(has(self.keyRelease) && has(self.keyRelease.required) && self.keyRelease.required) || self.keyRelease.ttlSeconds > 0",message="keyRelease.ttlSeconds must be > 0 when keyRelease.required is true"
type AIKeyReleasePolicySpec struct {
	// Target selects workloads or applications subject to key release.
	Target WorkloadTarget `json:"target"`

	// EvidenceRef references the required attestation evidence object.
	// +optional
	EvidenceRef *ObjectReference `json:"evidenceRef,omitempty"`

	// RequireAttestedEvidence blocks release when evidence is absent.
	// +optional
	RequireAttestedEvidence bool `json:"requireAttestedEvidence,omitempty"`

	// KeyRelease TTL governs the release artifact.
	// +optional
	KeyRelease PolicyKeyReleaseSpec `json:"keyRelease,omitempty"`

	// AllowedSecrets constrains releasable Kubernetes secrets.
	// +optional
	AllowedSecrets []corev1.LocalObjectReference `json:"allowedSecrets,omitempty"`

	// Audit controls audit retention detail.
	// +optional
	Audit PolicyAuditSpec `json:"audit,omitempty"`

	// EnforcementMode controls the gateway decision mode.
	// +kubebuilder:validation:Enum=warn;enforce;audit
	EnforcementMode string `json:"enforcementMode"`
}

type AIKeyReleasePolicyStatus struct {
	// ObservedGeneration is the last generation observed by a controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// LastDecision is allow, deny or pending.
	// +optional
	LastDecision string `json:"lastDecision,omitempty"`

	// LastDecisionTime is the last evaluated decision time.
	// +optional
	LastDecisionTime *metav1.Time `json:"lastDecisionTime,omitempty"`

	// Conditions captures readiness and release state.
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=akrp
type AIKeyReleasePolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AIKeyReleasePolicySpec   `json:"spec,omitempty"`
	Status AIKeyReleasePolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AIKeyReleasePolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIKeyReleasePolicy `json:"items"`
}

type AIEvidenceRecordSpec struct {
	// SubjectRef identifies the audited workload or decision.
	SubjectRef ObjectReference `json:"subjectRef"`

	// PolicyRef optionally ties the record to the policy that emitted it.
	// +optional
	PolicyRef *ObjectReference `json:"policyRef,omitempty"`

	// Category identifies the evidence category.
	// +kubebuilder:validation:Enum=attestation;placement;key-release;revocation;audit-checkpoint
	Category string `json:"category"`

	// PayloadDigest is the immutable digest of the stored payload.
	// +optional
	PayloadDigest string `json:"payloadDigest,omitempty"`

	// PreviousRecordDigest links the append-only chain.
	// +optional
	PreviousRecordDigest string `json:"previousRecordDigest,omitempty"`

	// ExternalCheckpointRef identifies the external anchoring checkpoint when present.
	// +optional
	ExternalCheckpointRef string `json:"externalCheckpointRef,omitempty"`

	// RetentionDays defines the retention objective for the record.
	// +kubebuilder:validation:Minimum=1
	// +optional
	RetentionDays int32 `json:"retentionDays,omitempty"`
}

type AIEvidenceRecordStatus struct {
	// ObservedGeneration is the last generation observed by a controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// ChainDigest is the materialized digest of this chain node.
	// +optional
	ChainDigest string `json:"chainDigest,omitempty"`

	// Anchored means the chain segment has been checkpointed externally.
	// +optional
	Anchored bool `json:"anchored,omitempty"`

	// Conditions captures audit state.
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=aier
type AIEvidenceRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AIEvidenceRecordSpec   `json:"spec,omitempty"`
	Status AIEvidenceRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AIEvidenceRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIEvidenceRecord `json:"items"`
}

type AIRevocationPolicySpec struct {
	// Target selects workloads, evidence subjects or decisions to revoke.
	Target WorkloadTarget `json:"target"`

	// EvidenceRef optionally points at the evidence object being revoked.
	// +optional
	EvidenceRef *ObjectReference `json:"evidenceRef,omitempty"`

	// PlacementRef optionally points at the placement decision being revoked.
	// +optional
	PlacementRef *ObjectReference `json:"placementRef,omitempty"`

	// Reasons documents why revocation is necessary.
	// +kubebuilder:validation:MinItems=1
	Reasons []string `json:"reasons,omitempty"`

	// TTLSeconds defines the bounded revocation window before reevaluation.
	// +kubebuilder:validation:Minimum=1
	TTLSeconds int32 `json:"ttlSeconds"`

	// Audit controls how much detail must be retained.
	// +optional
	Audit PolicyAuditSpec `json:"audit,omitempty"`
}

type AIRevocationPolicyStatus struct {
	// ObservedGeneration is the last generation observed by a controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Active indicates the revocation is currently enforced.
	// +optional
	Active bool `json:"active,omitempty"`

	// ExpiresAt is the bounded revocation expiry time.
	// +optional
	ExpiresAt *metav1.Time `json:"expiresAt,omitempty"`

	// Conditions captures revocation state.
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=airvp
type AIRevocationPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AIRevocationPolicySpec   `json:"spec,omitempty"`
	Status AIRevocationPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AIRevocationPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIRevocationPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(
		&ConfidentialInferencePolicy{}, &ConfidentialInferencePolicyList{},
		&AttestationEvidence{}, &AttestationEvidenceList{},
		&AIPlacementDecision{}, &AIPlacementDecisionList{},
		&AIKeyReleasePolicy{}, &AIKeyReleasePolicyList{},
		&AIEvidenceRecord{}, &AIEvidenceRecordList{},
		&AIRevocationPolicy{}, &AIRevocationPolicyList{},
	)
}

func (s ConfidentialInferencePolicySpec) Validate(path *field.Path) field.ErrorList {
	var errs field.ErrorList
	if s.RequireConfidentialGPU && s.GPU == nil {
		errs = append(errs, field.Required(path.Child("gpu"), "gpu is required when requireConfidentialGPU is true"))
	}
	if s.RequireConfidentialContainers && len(s.AllowedRuntimeClasses) == 0 {
		errs = append(errs, field.Required(path.Child("allowedRuntimeClasses"), "at least one runtime class is required"))
	}
	if s.KeyRelease.Required && s.KeyRelease.TTLSeconds <= 0 {
		errs = append(errs, field.Invalid(path.Child("keyRelease", "ttlSeconds"), s.KeyRelease.TTLSeconds, "must be > 0 when key release is required"))
	}
	return errs
}

func (s AIKeyReleasePolicySpec) Validate(path *field.Path) field.ErrorList {
	var errs field.ErrorList
	if s.RequireAttestedEvidence && s.EvidenceRef == nil {
		errs = append(errs, field.Required(path.Child("evidenceRef"), "evidenceRef is required when requireAttestedEvidence is true"))
	}
	if s.KeyRelease.Required && s.KeyRelease.TTLSeconds <= 0 {
		errs = append(errs, field.Invalid(path.Child("keyRelease", "ttlSeconds"), s.KeyRelease.TTLSeconds, "must be > 0 when key release is required"))
	}
	return errs
}

func (s AIRevocationPolicySpec) Validate(path *field.Path) field.ErrorList {
	var errs field.ErrorList
	if len(s.Reasons) == 0 {
		errs = append(errs, field.Required(path.Child("reasons"), "at least one revocation reason is required"))
	}
	for i, reason := range s.Reasons {
		if strings.TrimSpace(reason) == "" {
			errs = append(errs, field.Invalid(path.Child("reasons").Index(i), reason, "reason must not be empty"))
		}
	}
	return errs
}
