package govar

import (
	"context"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
)

func selectedFeedbackTestBinding(run, item string) *SelectedFeedbackBinding {
	return &SelectedFeedbackBinding{
		RunID: run, DatasetID: selectedFeedbackDataset, Split: "development", ItemID: eventPayloadHash(item),
		ProtocolSHA256: eventPayloadHash("selected-feedback-protocol"), OracleArtifactSHA256: eventPayloadHash("selected-feedback-oracle"),
		SoftwareSHA256: testCohortSoftwareHash, ConfigSHA256: eventPayloadHash("selected-feedback-config"),
	}
}

func selectedFeedbackAdmitRequest(id, run, item string) AdmitRequest {
	req := admitRequest(id, testTenant, testWorkload)
	req.SelectedFeedback = selectedFeedbackTestBinding(run, item)
	return req
}

func TestSelectedFeedbackAuthorizationMatchesPythonCanonicalVector(t *testing.T) {
	auth := selectedFeedbackAuthorization{
		DispatchID: strings.Repeat("5", 64), RequestID: strings.Repeat("6", 64), ItemID: strings.Repeat("7", 64),
		SelectedModelID: strings.Repeat("8", 64), SelectedDeployment: "routereval/model-a", AttemptID: strings.Repeat("9", 64),
		DecisionSHA256: strings.Repeat("a", 64), DispatchedAtUTC: "2026-07-14T00:00:00Z", ExpiresAtUTC: "2026-07-14T00:05:00Z",
		Binding: selectedFeedbackRunBinding{RunID: "cross-language-run", DatasetID: selectedFeedbackDataset, Split: "development",
			ProtocolSHA256: strings.Repeat("1", 64), OracleArtifactSHA256: strings.Repeat("2", 64),
			SoftwareSHA256: strings.Repeat("3", 64), ConfigSHA256: strings.Repeat("4", 64)},
	}
	got, err := selectedFeedbackCanonicalAuthorizationSHA256(auth)
	if err != nil {
		t.Fatal(err)
	}
	// Independently generated by DispatchAuthorization.authorization_sha256 in
	// article3/datasets/selected_feedback.py from the same literal record.
	const want = "4c50b67e53c36d32e18a0bc11cd883f6dbaa2841c65d31bced6fbcf59b6570e7"
	if got != want {
		t.Fatalf("canonical authorization SHA-256=%s want=%s", got, want)
	}
}

func TestSelectedFeedbackBoundDeliveryFailsClosedWithoutPostgres(t *testing.T) {
	e := NewEngine()
	if err := e.ConfigureCohortRuntime(testCohortSoftwareHash); err != nil {
		t.Fatal(err)
	}
	req := selectedFeedbackAdmitRequest("feedback-memory", "feedback-memory-run", "feedback-memory-item")
	admit, err := e.Admit(req, defaultBudget(), defaultRouting(), defaultCandidates())
	if err != nil || admit.Decision != DecisionAdmit {
		t.Fatalf("admit=(%+v,%v)", admit, err)
	}
	claim := dispatchRequest(req.RequestID, "feedback-memory-claim", admit.ProviderAttemptID, DispatchClaimed, testTenant, testWorkload)
	if _, code, err := e.Dispatch(claim); err != nil || code != ReasonDispatchClaimed {
		t.Fatalf("claim=(%s,%v)", code, err)
	}
	deliver := claim
	deliver.EventID, deliver.Status = "feedback-memory-deliver", DispatchDelivered
	if _, code, err := e.Dispatch(deliver); err == nil || code != ReasonInvalidTransition || !strings.Contains(err.Error(), "PostgreSQL authority") {
		t.Fatalf("in-memory delivery=(%s,%v)", code, err)
	}
	stored := e.reservations[req.RequestID]
	if stored.State != StateDispatchPending || stored.OutboxState != OutboxClaimed {
		t.Fatalf("in-memory failure changed state: %+v", stored)
	}
}

func selectedFeedbackOwnerQuery(t *testing.T, e *PostgresEngine, query string, args ...any) pgx.Row {
	t.Helper()
	conn, err := pgx.Connect(context.Background(), e.databaseURL)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = conn.Close(context.Background()) })
	return conn.QueryRow(context.Background(), query, args...)
}

func assertSelectedFeedbackRolledBack(t *testing.T, e *PostgresEngine, requestID, deliveredEventID, dispatchID string) {
	t.Helper()
	var state ReservationState
	var outbox OutboxState
	var inbox, authorization, dispatchAudits int
	err := selectedFeedbackOwnerQuery(t, e, `SELECT state,outbox_state,
 (SELECT count(*) FROM govar_inbox WHERE event_id=$2),
 (SELECT count(*) FROM govar_selected_feedback_dispatches WHERE dispatch_id=$3),
 (SELECT count(*) FROM govar_audit_events WHERE event_id=$2)
 FROM govar_reservations WHERE request_id=$1`, requestID, deliveredEventID, dispatchID).Scan(
		&state, &outbox, &inbox, &authorization, &dispatchAudits)
	if err != nil {
		t.Fatal(err)
	}
	if state != StateDispatchPending || outbox != OutboxClaimed || inbox != 0 || authorization != 0 || dispatchAudits != 0 {
		t.Fatalf("partial delivery survived rollback: state=%s outbox=%s inbox=%d authorization=%d audit=%d", state, outbox, inbox, authorization, dispatchAudits)
	}
}

func TestPostgresSelectedFeedbackAuthorizationIsAtomicWithEffectiveDispatch(t *testing.T) {
	url := os.Getenv("GOVAR_TEST_DATABASE_URL")
	if url == "" {
		t.Skip("GOVAR_TEST_DATABASE_URL is not set")
	}
	ctx := context.Background()
	e, err := NewPostgresEngine(ctx, url)
	if err != nil {
		t.Fatal(err)
	}
	defer e.Close()
	if err := e.ConfigureCohortRuntime(testCohortSoftwareHash); err != nil {
		t.Fatal(err)
	}
	if err := resetPostgresTestLedger(ctx, e); err != nil {
		t.Fatal(err)
	}
	now := time.Now().UTC().Truncate(time.Second)
	e.now = func() time.Time { return now }
	req := selectedFeedbackAdmitRequest("feedback-atomic", "feedback-atomic-run", "feedback-atomic-item")
	routing := defaultRoutingAt(now)
	if _, err := e.Admit(req, defaultBudget(), routing, defaultCandidates()); err == nil || !strings.Contains(err.Error(), "configured run authority") {
		t.Fatalf("unconfigured selected-feedback run was accepted: %v", err)
	}
	authority := authorityForSelectedFeedbackBinding(req.SelectedFeedback)
	if err := e.ConfigureSelectedFeedbackAuthority(authority); err != nil {
		t.Fatal(err)
	}
	if err := e.ConfigureSelectedFeedbackAuthority(authority); err != nil {
		t.Fatalf("exact authority replay: %v", err)
	}
	changedAuthority := authority
	changedAuthority.RunID = "feedback-reconfigured-run"
	if err := e.ConfigureSelectedFeedbackAuthority(changedAuthority); err == nil || !strings.Contains(err.Error(), "cannot be reconfigured") {
		t.Fatalf("authority reconfiguration=%v", err)
	}
	wrongRun := req
	wrongBinding := *req.SelectedFeedback
	wrongBinding.RunID = "feedback-attacker-changed-run"
	wrongRun.SelectedFeedback = &wrongBinding
	if _, err := e.Admit(wrongRun, defaultBudget(), routing, defaultCandidates()); err == nil || !strings.Contains(err.Error(), "configured run authority") {
		t.Fatalf("caller-selected run identity was accepted: %v", err)
	}
	admit, err := e.Admit(req, defaultBudget(), routing, defaultCandidates())
	if err != nil || admit.Decision != DecisionAdmit {
		t.Fatalf("admit=(%+v,%v)", admit, err)
	}
	claim := dispatchRequest(req.RequestID, "feedback-atomic-claim", admit.ProviderAttemptID, DispatchClaimed, testTenant, testWorkload)
	if _, code, err := e.Dispatch(claim); err != nil || code != ReasonDispatchClaimed {
		t.Fatalf("claim=(%s,%v)", code, err)
	}

	readTx, err := e.pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	reserved, err := loadReservationTx(ctx, readTx, req.RequestID, false)
	_ = readTx.Rollback(ctx)
	if err != nil || reserved.SelectedFeedback == nil || reserved.SelectedFeedbackBindingSHA256 != selectedFeedbackBindingSHA256(req.SelectedFeedback) {
		t.Fatalf("pre-admission binding persistence=(%+v,%v)", reserved.SelectedFeedback, err)
	}
	predictedDispatchID := selectedFeedbackDispatchID(reserved)
	var authorizations int
	if err := selectedFeedbackOwnerQuery(t, e, `SELECT count(*) FROM govar_selected_feedback_dispatches`).Scan(&authorizations); err != nil || authorizations != 0 {
		t.Fatalf("authorization existed before delivery: count=%d err=%v", authorizations, err)
	}
	// The evaluator cannot commit an outcome before the delivery transaction
	// creates the authorization row.
	err = postgresOwnerExec(ctx, e, `INSERT INTO govar_selected_feedback_commitments(
dispatch_id,run_id,request_id,item_id,selected_model_id,selected_score,authorization_sha256,committed_at_utc,commitment_sha256)
VALUES($1,$2,$3,$4,$5,1,$6,clock_timestamp(),$7)`, predictedDispatchID, req.SelectedFeedback.RunID,
		selectedFeedbackTextSHA256(req.RequestID), req.SelectedFeedback.ItemID, authority.SelectedModelIDs[admit.SelectedDeployment],
		eventPayloadHash("not-authorized"), eventPayloadHash("not-authorized-commitment"))
	if err == nil {
		t.Fatal("selected-feedback outcome commitment succeeded before effective dispatch")
	}

	deliver := claim
	deliver.EventID, deliver.Status = "feedback-atomic-deliver", DispatchDelivered
	delivered, code, err := e.Dispatch(deliver)
	if err != nil || code != ReasonDispatchDelivered || !delivered.TransitionEffective || delivered.SelectedFeedbackDispatchID != predictedDispatchID {
		t.Fatalf("deliver=(%+v,%s,%v)", delivered, code, err)
	}
	expected, err := buildSelectedFeedbackAuthorization(delivered, now, authority)
	if err != nil {
		t.Fatal(err)
	}
	var got selectedFeedbackAuthorization
	err = selectedFeedbackOwnerQuery(t, e, `SELECT dispatch_id,run_id,dataset_id,split,request_id,item_id,selected_model_id,
selected_deployment,attempt_id,decision_sha256,protocol_sha256,oracle_artifact_sha256,software_sha256,config_sha256,
to_char(dispatched_at_utc AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'),
to_char(expires_at_utc AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'),authorization_sha256
FROM govar_selected_feedback_dispatches WHERE dispatch_id=$1`, predictedDispatchID).Scan(
		&got.DispatchID, &got.Binding.RunID, &got.Binding.DatasetID, &got.Binding.Split, &got.RequestID, &got.ItemID,
		&got.SelectedModelID, &got.SelectedDeployment, &got.AttemptID, &got.DecisionSHA256,
		&got.Binding.ProtocolSHA256, &got.Binding.OracleArtifactSHA256, &got.Binding.SoftwareSHA256,
		&got.Binding.ConfigSHA256, &got.DispatchedAtUTC, &got.ExpiresAtUTC, &got.AuthorizationSHA256)
	if err != nil {
		t.Fatal(err)
	}
	if got != expected {
		t.Fatalf("authorization binding differs\ngot:  %+v\nwant: %+v", got, expected)
	}
	if got.SelectedModelID != authority.SelectedModelIDs[delivered.SelectedDeployment] ||
		got.SelectedModelID == selectedFeedbackTextSHA256(delivered.SelectedDeployment) {
		t.Fatalf("authorization used deployment-derived model identity: %+v", got)
	}

	replayed, code, err := e.Dispatch(deliver)
	if err != nil || code != ReasonDuplicateEvent || replayed.TransitionEffective || replayed.SelectedFeedbackDispatchID != predictedDispatchID {
		t.Fatalf("replay=(%+v,%s,%v)", replayed, code, err)
	}
	if err := selectedFeedbackOwnerQuery(t, e, `SELECT count(*) FROM govar_selected_feedback_dispatches WHERE dispatch_id=$1`, predictedDispatchID).Scan(&authorizations); err != nil || authorizations != 1 {
		t.Fatalf("replay authorization count=%d err=%v", authorizations, err)
	}
}

func TestPostgresSelectedFeedbackConflictAndInsertFailureRollBackDelivery(t *testing.T) {
	url := os.Getenv("GOVAR_TEST_DATABASE_URL")
	if url == "" {
		t.Skip("GOVAR_TEST_DATABASE_URL is not set")
	}
	ctx := context.Background()
	e, err := NewPostgresEngine(ctx, url)
	if err != nil {
		t.Fatal(err)
	}
	defer e.Close()
	if err := e.ConfigureCohortRuntime(testCohortSoftwareHash); err != nil {
		t.Fatal(err)
	}
	if err := resetPostgresTestLedger(ctx, e); err != nil {
		t.Fatal(err)
	}
	now := time.Now().UTC().Truncate(time.Second)
	e.now = func() time.Time { return now }
	routing := defaultRoutingAt(now)
	authorityBinding := selectedFeedbackTestBinding("feedback-conflict-run", "authority-unused-item")
	if err := e.ConfigureSelectedFeedbackAuthority(authorityForSelectedFeedbackBinding(authorityBinding)); err != nil {
		t.Fatal(err)
	}

	// Two pre-admission reservations for one run/item may race, but the unique
	// authorization insert lets only one delivery become effective.
	var reservations []Reservation
	for _, id := range []string{"feedback-conflict-a", "feedback-conflict-b"} {
		req := selectedFeedbackAdmitRequest(id, "feedback-conflict-run", "one-item")
		admit, err := e.Admit(req, defaultBudget(), routing, defaultCandidates())
		if err != nil || admit.Decision != DecisionAdmit {
			t.Fatalf("admit %s=(%+v,%v)", id, admit, err)
		}
		claim := dispatchRequest(id, id+"-claim", admit.ProviderAttemptID, DispatchClaimed, testTenant, testWorkload)
		if _, _, err := e.Dispatch(claim); err != nil {
			t.Fatal(err)
		}
		readTx, err := e.pool.Begin(ctx)
		if err != nil {
			t.Fatal(err)
		}
		stored, loadErr := loadReservationTx(ctx, readTx, id, false)
		_ = readTx.Rollback(ctx)
		if loadErr != nil {
			t.Fatal(loadErr)
		}
		reservations = append(reservations, stored)
	}
	first := dispatchRequest("feedback-conflict-a", "feedback-conflict-a-deliver", reservations[0].ProviderAttemptID, DispatchDelivered, testTenant, testWorkload)
	if _, code, err := e.Dispatch(first); err != nil || code != ReasonDispatchDelivered {
		t.Fatalf("first delivery=(%s,%v)", code, err)
	}
	second := dispatchRequest("feedback-conflict-b", "feedback-conflict-b-deliver", reservations[1].ProviderAttemptID, DispatchDelivered, testTenant, testWorkload)
	if _, _, err := e.Dispatch(second); err == nil {
		t.Fatal("second delivery for the same immutable run/item was accepted")
	}
	assertSelectedFeedbackRolledBack(t, e, second.RequestID, second.EventID, selectedFeedbackDispatchID(reservations[1]))

	// A materially different database failure at the authorization boundary
	// also rolls back outbox, reservation, inbox, and audit changes.
	req := selectedFeedbackAdmitRequest("feedback-forced-failure", "feedback-conflict-run", "forced-item")
	admit, err := e.Admit(req, defaultBudget(), routing, defaultCandidates())
	if err != nil {
		t.Fatal(err)
	}
	claim := dispatchRequest(req.RequestID, "feedback-forced-failure-claim", admit.ProviderAttemptID, DispatchClaimed, testTenant, testWorkload)
	if _, _, err := e.Dispatch(claim); err != nil {
		t.Fatal(err)
	}
	readTx, err := e.pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	stored, err := loadReservationTx(ctx, readTx, req.RequestID, false)
	_ = readTx.Rollback(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if err := postgresOwnerExec(ctx, e, `CREATE OR REPLACE FUNCTION govar_test_reject_feedback_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced selected-feedback insert failure'; END $$;
CREATE TRIGGER govar_test_reject_feedback_insert BEFORE INSERT ON govar_selected_feedback_dispatches FOR EACH ROW EXECUTE FUNCTION govar_test_reject_feedback_insert()`); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = postgresOwnerExec(context.Background(), e, `DROP TRIGGER IF EXISTS govar_test_reject_feedback_insert ON govar_selected_feedback_dispatches; DROP FUNCTION IF EXISTS govar_test_reject_feedback_insert()`)
	})
	deliver := dispatchRequest(req.RequestID, "feedback-forced-failure-deliver", admit.ProviderAttemptID, DispatchDelivered, testTenant, testWorkload)
	if _, _, err := e.Dispatch(deliver); err == nil || !strings.Contains(err.Error(), "forced selected-feedback insert failure") {
		t.Fatalf("forced authorization failure=%v", err)
	}
	assertSelectedFeedbackRolledBack(t, e, req.RequestID, deliver.EventID, selectedFeedbackDispatchID(stored))
}

func TestPostgresSelectedFeedbackRuntimeRoleIsLeastPrivilege(t *testing.T) {
	url := os.Getenv("GOVAR_TEST_DATABASE_URL")
	if url == "" {
		t.Skip("GOVAR_TEST_DATABASE_URL is not set")
	}
	ctx := context.Background()
	e, err := NewPostgresEngine(ctx, url)
	if err != nil {
		t.Fatal(err)
	}
	defer e.Close()
	var dispatchInsert, dispatchSelect, commitmentsSelect, commitmentsInsert, observationsSelect, observationsInsert bool
	err = e.pool.QueryRow(ctx, `SELECT
has_table_privilege(current_user,'govar_selected_feedback_dispatches','INSERT'),
has_table_privilege(current_user,'govar_selected_feedback_dispatches','SELECT'),
has_table_privilege(current_user,'govar_selected_feedback_commitments','SELECT'),
has_table_privilege(current_user,'govar_selected_feedback_commitments','INSERT'),
has_table_privilege(current_user,'govar_selected_feedback_observations','SELECT'),
has_table_privilege(current_user,'govar_selected_feedback_observations','INSERT')`).Scan(
		&dispatchInsert, &dispatchSelect, &commitmentsSelect, &commitmentsInsert, &observationsSelect, &observationsInsert)
	if err != nil {
		t.Fatal(err)
	}
	if !dispatchInsert || dispatchSelect || commitmentsSelect || commitmentsInsert || observationsSelect || observationsInsert {
		t.Fatalf("runtime selected-feedback privileges insert=%t select=%t commitments=(%t,%t) observations=(%t,%t)",
			dispatchInsert, dispatchSelect, commitmentsSelect, commitmentsInsert, observationsSelect, observationsInsert)
	}
	var owner, superuser bool
	err = e.pool.QueryRow(ctx, `SELECT pg_get_userbyid(c.relowner)=current_user,
COALESCE((SELECT rolsuper FROM pg_roles WHERE rolname='govar_runtime'),false)
FROM pg_class c WHERE c.oid='govar_selected_feedback_dispatches'::regclass`).Scan(&owner, &superuser)
	if err != nil {
		t.Fatal(err)
	}
	if owner || superuser {
		t.Fatalf("runtime role owns selected-feedback table or is superuser: owner=%t superuser=%t", owner, superuser)
	}
}
